'use strict';

module.exports = {
	types: {
		TYPE_MODULE: 0,
		TYPE_VARIABLE_DECLARATION: 1,
		TYPE_VARIABLE_DECLARATOR: 2,
		TYPE_IDENTIFIER: 3,
		TYPE_NUMERIC_LITERAL: 4
	},
	varKinds: {
		VAR_KIND_VAR: 0,
		VAR_KIND_LET: 1,
		VAR_KIND_CONST: 2
	},
	VAR_KIND_MASK: 3,
	VAR_DECLARE_MASK: 4
};
